config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  get 'alarms/refresh' => 'alarms#refresh', as: :refresh_alarms

  get 'alarms/all' => 'alarms#all', as: :all_alarms

  resources :alarms do
resources :notifications
end

devise_scope :admin do
  authenticated :admin do
    root :to => 'alarms#index'
  end
  unauthenticated :admin do
    root :to => 'devise/registrations#new', as: :unauthenticated_root
  end
end  # Example of regular route:

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/alarm.rb
class Alarm < ActiveRecord::Base	
	
	has_many :notifications, :dependent => :destroy
	def name
	first_name + " " + last_name
	end
	validates :first_name,presence: true, length:{:in=>2..50, message: "Debe tener entre 2 y 50 caracateres"}
	validates :last_name,presence: true, length:{:in=>2..50, :message => "Debe tener entre 2 y 50 caracateres"}
	validates :email,presence: true, length:{:in=>2..50, :message => "Debe tener entre 2 y 50 caracateres"}
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

	validates :key,presence: true,:numericality => { :only_integer => true , :message => "Debe contener solo numeros"}
	validates :phone,presence: true,:numericality => { :only_integer => true , :message => "Debe contener solo numeros"}
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :alarm
	validates_existence_of :alarm, :both => false
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]


def refresh
    # render the partial for alarms table back to the ajax request
    # which will be the contents of data and be inserted into the tbody
    render :partial => 'alarms/alarms_table', :format => 'text/html', :locals => {:alarms => Alarm.all}
  end

 def all
    @alarms = Alarm.all.includes(:notifications)
  end

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all.includes(:notifications)
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to @alarm, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:ip, :first_name, :email, :last_name, :address, :key, :phone)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_admin!

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
before_filter :get_alarm, only: [:index, :show, :edit, :update, :destroy]
# :get_alarm is defined at the bottom of the file,
# and takes the alarm_id given by the routing and
# converts it to an @alarm object.
def refresh
    # render the partial for notifications table back to the ajax request
    # which will be the contents of data and be inserted into the tbody
#    render :partial => 'notifications/notifications_table', :format => 'text/html', :locals => {:notifications => Notification.all}
 #render :partial => 'notifications/notifications_table', :format => 'text/html', :locals => {:notifications => @alarm.notifications}
    #render :partial => 'notifications/notifications_table', :format => 'text/html', locals: { notifications: @alarm.notifications}

  end
def all
@all_notifications=Notification.all
end

def index
@notifications = @alarm.notifications
# was @notifications = Notification.find(:all)
	respond_to do |format|
	format.html # index.html.erb
	format.json { render json: @notifications }
	end
end
# GET /notifications/1
# GET /notifications/1.json
def show
@notification = @alarm.notifications.find(params[:id])
# was Notification.find(params[:id])
	respond_to do |format|
	format.html # show.html.erb
	format.json { render json: @notification }
	end
end
# GET /notifications/new
# GET /notifications/new.json
def new
@alarm = Alarm.find(params[:alarm_id])
@notification = @alarm.notifications.build
# was @notification = Notification.new
	respond_to do |format|
	format.html # new.html.erb
	format.json { render json: @notification }
	end
end
# GET /notifications/1/edit
def edit
@notification = @alarm.notifications.find(params[:id])
# was @notification = Notification.find(params[:id])
end
# POST /notifications
# POST /notifications.json
def create
	# @notification = @alarm.notifications.build(params[:notification])
	 @notification = @alarm.notifications.build(notification_params)

	# was @notification = Notification.new(params[:notification])
	respond_to do |format|
		if @notification.save
		format.html { redirect_to alarm_notifications_url(@alarm), notice:
		'Notification was successfully created.' }
		# was redirect_to(@notification)
		format.json { render json: @notification, status: :created, location: @notification }
		else
		format.html { render action: "new" }
		format.json { render json: @notification.errors, status: :unprocessable_entity }
		end
	end	
end
# PUT /notifications/1
# PUT /notifications/1.json
def update
	@notification = @alarm.notifications.find(params[:id])
	# was @notification = Notification.find(params[:id])
	respond_to do |format|
		if @notification.update_attributes(notification_params)
		format.html { redirect_to alarm_notifications_url(@alarm), notice:
		'Notification was successfully updated.' }
		# was redirect_to(@notification)
		format.json { head :ok }
		else
		format.html { render action: "edit" }
		format.json { render json: @notification.errors, status: :unprocessable_entity }
		end
	end
end
# DELETE /notifications/1
# DELETE /notifications/1.json
def destroy
@notification = @alarm.notifications.find(params[:id])
# was @notification = Notification.find(params[:id])
@notification.destroy
respond_to do |format|
format.html { redirect_to (alarm_notifications_path(@alarm)) }
# was redirect_to(notifications_url)
format.json { head :ok }
	end
end
private
# get_alarm converts the alarm_id given by the routing
# into an @alarm object, for use here and in the view.
	def get_alarm
	@alarm = Alarm.find(params[:alarm_id])
	end
	def notification_params
    params.require(:notification).permit(:id, :ip, :zones, :alarm_id, :alert)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/alarms/_alarms_table.html.erb
<% alarms.each do |alarm| %>
       <% alarm.notifications.each do |notification| %>
<% if notification.alert !=0 %>
          <tr class="success">
            <td><%= alarm.id %></td>
            <td><%= alarm.first_name %> <%= alarm.last_name %></td>
            <td><%= notification.zones %></td>
            <td><%= link_to 'Ver', [alarm,notification], class: 'btn btn-info btn-xl' %></td>
          </tr>
<% end %>                
        <% end %>      
<% end %>

app/views/alarms/_all_alarms_table.html.erb
<% alarms.each do |alarm| %>
          <tr class="success">
            <td><%= alarm.id %></td>
            <td><%= alarm.first_name %> <%= alarm.last_name %></td>
            <td><%= alarm.notifications.count %></td>
            <td><%= link_to 'Detalles', alarm, class: 'btn btn-success btn-xs' %></td>
            <td><%= link_to 'Editar', edit_alarm_path(alarm), class: 'btn btn-warning btn-xs' %></td>
            <td><%= link_to 'Notificaciones', alarm_notifications_path(alarm), class: 'btn btn-info btn-xs' %></td>
            <td><%= link_to 'Borrar', alarm, method: :delete, data: { confirm: 'Esta seguro?' } , class: 'btn btn-danger btn-xs',:remote => true %> </td>
          </tr>
<% end %>

app/views/alarms/_form.html.erb
<%= form_for(@alarm) do |f| %>
  <% if @alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% @alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
 
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  
   <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alarms/all.html.erb
<p id="notice"><%= notice %></p>

<h1 class="yellow_title"> Listado de Alarmas</h1>

  <table class="table  table-bordered table-hover ">
  <thead>
    <tr class="warning">
      <th>ID</th>
      <th>Nombre</th>
      <th>Notificaciones</th>
      <th></th>
      <th>Options</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody id="alarmstbody">
    <%= render 'all_alarms_table', :alarms => @alarms %>
  </tbody>
</table>

</table>

<br>

<%= link_to 'Alertas', '/', class: 'btn btn-warning btn-lg'  %>
<%= link_to 'Nueva Alarma', new_alarm_path, class: 'btn btn-warning btn-lg'  %>

app/views/alarms/destroy.js.erb
$('.delete_pony').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form' %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="yellow_title"> Listado de Alertas</h1>

  <table class="table  table-bordered table-hover ">
  <thead>
    <tr class="warning">
      <th>ID</th>
      <th>Nombre</th>
      <th>Alerta-zona</th>
      <th>Options</th>
    </tr>
  </thead>

 <tbody id="alarmstbody">
    <%= render 'alarms_table', :alarms => @alarms %>
  </tbody>
</table>

</table>

<br>

<%= link_to 'Nueva Alarma', new_alarm_path, class: 'btn btn-warning btn-lg'  %>

<%= link_to 'Todos los Usuarios', '/alarms/all', class: 'btn btn-warning btn-lg'  %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form' %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Detalles<h2>
<p>
  <strong>Nombre</strong>
  <%= @alarm.first_name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @alarm.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @alarm.email %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @alarm.address %>
</p>

<p>
  <strong>Key:</strong>
  <%= @alarm.key %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @alarm.phone %>
</p>

<h3>Notificaciones</h3>
  <table class="table table-striped">
<tr>
<th>IP</th>
<th>Zonas</th>
</tr>
<% for notification in @alarm.notifications %>
<tr>
<td><%= notification.ip %></td>
<td><%= notification.zones %></td>
</tr>
<% end %>
</table>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> 
<%= link_to 'Notifications', alarm_notifications_path(@alarm) %> ||
<%= link_to 'Back', alarms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistema de Notificaciones</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= render 'shared/navigation' %>

<%= yield %>

</body>
</html>

app/views/notifications/_form.html.erb
<%= simple_form_for([@alarm, @notification]) do |f| %>
<% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.input :ip, :required => :true %>
  <%= f.input :zones, :required => :true %>
  <%= f.input :alert, :as => :boolean %>
  <%= f.button :submit %>
<% end -%>

app/views/notifications/_notifications_table.html.erb
<% notifications.each do |notification| %>
    <tr>
		<td><%= notification.alarm_id %></td>
		<td><%= notification.ip %></td>
		<td><%= notification.zones %></td>
		<td><%= notification.alert %></td>
		<td><%= link_to 'Mostrar', [@alarm, notification] %></td>
		<td><%= link_to 'Editar', edit_alarm_notification_path(@alarm, notification) %></td>
		<td><%= link_to 'Borrar', [@alarm, notification], :confirm => 'Esta seguro?',
		:method => :delete %></td>
	</tr>
<% end %>

app/views/notifications/all.html.erb
<h1>Notificaciones</h1>
<% if !@all_notifications.empty? %>
  <table class="table table-bordered">
		<tr>
			<th>ID</th>
			<th>IP</th>
			<th>zones</th>
			<th></th>
			<th>Opciones</th>
			<th></th>
		</tr>

		<% @all_notifications.each do |notification| %>
    <tr>
		<td><%= notification.alarm_id %></td>
		<td><%= notification.ip %></td>
		<td><%= notification.zones %></td>
		<td><%= link_to 'Inicio', '/' %></td>
		
	</tr>
<% end %>
	</table>

<br />

<% else %>
	<p> No hay Notificaciones.</p>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editar notificacion de <%= @alarm.first_name %></h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [@alarm, @notification] %> |
<%= link_to 'Volver', alarm_notifications_path(@alarm) %>

app/views/notifications/index.html.erb
<h1>Notificaciones de <%= @alarm.first_name %></h1>
<% if !@alarm.notifications.empty? %>
  <table class="table table-bordered">
		<tr>
			<th>ID</th>
			<th>IP</th>
			<th>zones</th>
			<th>alerta?</th>
			<th></th>
			<th>Options</th>
			<th></th>
		</tr>

		<tbody id="notificationstbody">
	    <%= render 'notifications_table', :notifications => @notifications %>
	  	</tbody>
	</table>

<br />

<% else %>
	<p><%= @alarm.first_name %> hasn't won any notifications yet.</p>
<% end %>

<p>
<a href="#" id="refresh">Refresh With Ajax</a>

	<%= link_to 'Nueva notificacion', new_alarm_notification_path(@alarm) %> |
	<%= link_to 'Volver', @alarm %>
</p>

app/views/notifications/new.html.erb
<h1>New notification for <%= @alarm.first_name %></h1>

<%= render 'form' %>

<%= link_to 'Back', alarm_notifications_path(@alarm) %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>IP:</strong>
  <%= @notification.ip%>
</p>

<p>
  <strong>Zonas:</strong>
  <%= @notification.zones %>
</p>

<p>
  <strong>Alarma:</strong>
<%= @notification.alarm.first_name %> <%= @notification.alarm.last_name %>
</p>

<p>
  <strong>Alerta?:</strong>
  <%= @notification.alert %>
</p>

<p>
  <strong>Creada:</strong>
  <%= @notification.created_at %>
</p>

<p>
  <strong>Actualizada:</strong>
  <%= @notification.updated_at %>
</p>
<%= link_to 'Edit', edit_alarm_notification_path(@alarm, @notification) %> |
<%= link_to 'Back', alarm_notifications_path(@alarm) %>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Inicio</a>
    </div>
  </div>
</nav>